import jsPDF from "jspdf";
import { useState } from "react";
import "./App.css";

function App() {
  const [file, setFile] = useState(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [dragOver, setDragOver] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);
  const [chatMessages, setChatMessages] = useState([]);
const [chatInput, setChatInput] = useState("");
const [chatLoading, setChatLoading] = useState(false);

const loadingMessages = [
  "Reading your document...",
  "Extracting clauses...",
  "Detecting red flags...",
  "Calculating risk score...",
  "Almost done...",
];
  const [showHowItWorks, setShowHowItWorks] = useState(false);
  const [showFeatures, setShowFeatures] = useState(false);

  const handleUpload = async (selectedFile) => {
  const f = selectedFile || file;
  if (!f) return alert("Please select a PDF file!");
  setLoading(true);
  setLoadingStep(0);

  const stepInterval = setInterval(() => {
    setLoadingStep((prev) => (prev < loadingMessages.length - 1 ? prev + 1 : prev));
  }, 3000);

  const formData = new FormData();
  formData.append("file", f);
  try {
    const res = await fetch("http://localhost:8000/upload", {
      method: "POST",
      body: formData,
    });
    const data = await res.json();
    setResult(data);
  } catch (err) {
    alert("Something went wrong. Make sure backend is running.");
  }
  clearInterval(stepInterval);
  setLoading(false);
};

  const handleDrop = (e) => {
    e.preventDefault();
    setDragOver(false);
    const dropped = e.dataTransfer.files[0];
    if (dropped && dropped.type === "application/pdf") {
      setFile(dropped);
      handleUpload(dropped);
    }
  };

  const downloadReport = () => {
  if (!result || !result.analysis) return;
  const a = result.analysis;
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  const addText = (text, fontSize, isBold, color, spacing = 7) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, maxWidth);
    lines.forEach((line) => {
      if (y > 280) { doc.addPage(); y = 20; }
      doc.text(line, margin, y);
      y += spacing;
    });
  };

  addText("LegalEase — Document Analysis Report", 18, true, [108, 99, 255], 10);
  addText(`File: ${result.filename}`, 11, false, [80, 80, 80], 6);
  addText(`Pages: ${result.pages}`, 11, false, [80, 80, 80], 6);
  addText(`Risk Level: ${a.risk_level}`, 12, true, [220, 38, 38], 10);

  addText("Summary", 14, true, [30, 27, 75], 8);
  addText(a.summary, 11, false, [40, 40, 40], 6);
  addText(`Why: ${a.risk_reason}`, 10, false, [100, 100, 100], 10);

  addText(`Red Flags (${a.red_flags.length})`, 14, true, [220, 38, 38], 8);
  a.red_flags.forEach((flag, i) => {
    addText(`${i + 1}. [${flag.severity}] ${flag.title}`, 11, true, [30, 27, 75], 6);
    addText(flag.description, 10, false, [60, 60, 60], 6);
    if (flag.suggestion) {
      addText(`Suggestion: ${flag.suggestion}`, 10, false, [108, 99, 255], 8);
    } else {
      y += 2;
    }
  });

  addText(`Clause Breakdown (${a.clauses.length})`, 14, true, [30, 27, 75], 8);
  a.clauses.forEach((clause, i) => {
    addText(`${i + 1}. [${clause.risk}] ${clause.name}`, 11, true, [30, 27, 75], 6);
    addText(clause.plain_english, 10, false, [60, 60, 60], 8);
  });

  addText("Generated by LegalEase — AI Legal Document Analyzer", 9, false, [150, 150, 150], 6);

  doc.save(`${result.filename.replace(".pdf", "")}_legalease_report.pdf`);
};


const sendChatMessage = async () => {
  if (!chatInput.trim() || !result) return;
  const question = chatInput.trim();
  setChatInput("");
  const newMessages = [...chatMessages, { role: "user", content: question }];
  setChatMessages(newMessages);
  setChatLoading(true);

  try {
    const res = await fetch("http://localhost:8000/chat", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        document_text: result.text,
        question: question,
        chat_history: chatMessages,
      }),
    });
    const data = await res.json();
    setChatMessages([...newMessages, { role: "assistant", content: data.answer }]);
  } catch (err) {
    setChatMessages([...newMessages, { role: "assistant", content: "Sorry, something went wrong. Please try again." }]);
  }
  setChatLoading(false);
};

  const getRiskColor = (risk) => {
    if (risk === "High") return "#f87171";
    if (risk === "Medium") return "#fbbf24";
    return "#4ade80";
  };

  const a = result && result.analysis;

  return (
    <div className="app">

      <nav className="navbar">
        <div className="brand">
          <span className="brand-icon">⚖️</span>
          <span className="brand-name">LegalEase</span>
          <span className="brand-badge">AI Powered</span>
        </div>
        <div className="nav-links">
          <div className="nav-links">
  <button className="nav-link" onClick={() => setShowHowItWorks(true)}>How it works</button>
  <button className="nav-link" onClick={() => setShowFeatures(true)}>Features</button>
  <button className="nav-solid" onClick={() => {
  setResult(null);
  setFile(null);
  window.scrollTo({ top: 0, behavior: "smooth" });
}}>
  Get started
</button>
</div>
        </div>
      </nav>

      {!result && (
        <div className="hero">
          <div className="hero-pill">
            <span className="green-dot"></span>
            AI analysis ready — try it free
          </div>
          <h1 className="hero-title">
            Understand any legal<br />
            <span className="hero-gradient">document instantly</span>
          </h1>
          <p className="hero-sub">
            Upload contracts, NDAs, rental agreements — get plain English summaries,
            red flag detection, risk scores, and an AI chatbot for your questions.
          </p>
          <div className="hero-pills">
            <span className="hero-pill-item">📄 Contracts</span>
            <span className="hero-pill-item">🏠 Rental Agreements</span>
            <span className="hero-pill-item">💼 Employment Letters</span>
            <span className="hero-pill-item">🤝 NDAs</span>
            <span className="hero-pill-item">🌍 100+ Languages</span>
          </div>
          <div className="hero-stats">
            <div className="hero-stat">
              <div className="stat-val">50K+</div>
              <div className="stat-label">Documents analyzed</div>
            </div>
            <div className="hero-stat">
              <div className="stat-val">98%</div>
              <div className="stat-label">Accuracy rate</div>
            </div>
            <div className="hero-stat">
              <div className="stat-val">&lt;30s</div>
              <div className="stat-label">Analysis time</div>
            </div>
            <div className="hero-stat">
              <div className="stat-val">100+</div>
              <div className="stat-label">Languages</div>
            </div>
          </div>
        </div>
      )}

      <div className="main">
        {!result && (
          <div
            className={`upload-box ${dragOver ? "drag-active" : ""}`}
            onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
            onDragLeave={() => setDragOver(false)}
            onDrop={handleDrop}
          >
            <div className="upload-icon-wrap">📤</div>
            <h2 className="upload-title">Drop your legal document here</h2>
            <p className="upload-sub">Supports PDF up to 50MB</p>
            <label className="upload-btn">
              <input
                type="file"
                accept=".pdf"
                onChange={(e) => setFile(e.target.files[0])}
                hidden
              />
              Upload PDF File
            </label>
            {file && <p className="file-selected">✅ {file.name}</p>}
            {file && (
  <button className="analyze-btn" onClick={() => handleUpload()} disabled={loading}>
    {loading ? <><span className="spinner"></span> Analyzing...</> : "🔍 Analyze Document"}
  </button>
)}
{loading && (
  <div className="loading-progress">
    <p className="loading-note">{loadingMessages[loadingStep]}</p>
    <div className="loading-bar">
      <div className="loading-bar-fill" style={{ width: `${((loadingStep + 1) / loadingMessages.length) * 100}%` }}></div>
    </div>
  </div>
)}
            <p className="privacy-note">🔒 Your document is never stored</p>
          </div>
        )}

        {result && a && (
          <div className="results">

            <div className="result-header">
              <div>
                <h2 className="result-title">Analysis Complete</h2>
                <p className="result-file">📄 {result.filename} — {result.pages} pages</p>
              </div>
              <button className="btn-secondary" onClick={() => { setResult(null); setFile(null); }}>
                Analyze New Document
              </button>
            </div>

            <div className="stats-grid">
              <div className="stat-card">
                <div className="sc-label">Risk Level</div>
                <div className="sc-val" style={{color: getRiskColor(a.risk_level)}}>{a.risk_level}</div>
              </div>
              <div className="stat-card">
                <div className="sc-label">Red Flags</div>
                <div className="sc-val" style={{color:"#f87171"}}>{a.red_flags.length}</div>
              </div>
              <div className="stat-card">
                <div className="sc-label">Clauses Found</div>
                <div className="sc-val" style={{color:"#818cf8"}}>{a.clauses.length}</div>
              </div>
              <div className="stat-card">
                <div className="sc-label">Pages</div>
                <div className="sc-val" style={{color:"#4ade80"}}>{result.pages}</div>
              </div>
            </div>

            <div className="card">
              <div className="card-header">
                <span className="card-icon">📋</span>
                <span className="card-title">Document Summary</span>
              </div>
              <div className="card-body">
                <p className="summary-text">{a.summary}</p>
                <div className="risk-reason">
                  <span style={{color: getRiskColor(a.risk_level)}}>⚠ </span>
                  {a.risk_reason}
                </div>
              </div>
            </div>

            {a.red_flags.length > 0 && (
              <div className="card">
                <div className="card-header">
                  <span className="card-icon">🚩</span>
                  <span className="card-title">Red Flags Detected</span>
                  <span className="badge-red">{a.red_flags.length} issues</span>
                </div>
                <div className="flags-list">
                  {a.red_flags.map((flag, i) => (
  <div key={i} className={`flag-item ${flag.severity === "High" ? "flag-red" : "flag-amber"}`}>
    <div className="flag-top">
      <span>{flag.severity === "High" ? "🔴" : "🟡"}</span>
      <span className="flag-title" style={{color: flag.severity === "High" ? "#f87171" : "#fbbf24"}}>
        {flag.title}
      </span>
    </div>
    <p className="flag-desc">{flag.description}</p>
    {flag.suggestion && (
      <div className="flag-suggestion">
        <span className="suggestion-label">💡 Try saying:</span>
        <p>{flag.suggestion}</p>
      </div>
    )}
  </div>
))}
                </div>
              </div>
            )}

            <div className="card">
              <div className="card-header">
                <span className="card-icon">📑</span>
                <span className="card-title">Clause Breakdown</span>
              </div>
              <div className="clauses-list">
                {a.clauses.map((clause, i) => (
                  <div key={i} className="clause-item">
                    <div className="clause-top">
                      <span className="clause-name">{clause.name}</span>
                      <span className="risk-badge" style={{
                        background: clause.risk === "High" ? "rgba(239,68,68,0.15)" : clause.risk === "Medium" ? "rgba(251,191,36,0.15)" : "rgba(34,197,94,0.15)",
                        color: clause.risk === "High" ? "#f87171" : clause.risk === "Medium" ? "#fbbf24" : "#4ade80"
                      }}>
                        {clause.risk}
                      </span>
                    </div>
                    <p className="clause-desc">{clause.plain_english}</p>
                  </div>
                ))}
              </div>
            </div>

            <div className="card">
  <div className="card-header">
    <span className="card-icon">💬</span>
    <span className="card-title">Ask your document</span>
  </div>
  <div className="chat-box">
    {chatMessages.length === 0 && (
      <p className="chat-empty">Ask anything about this document — e.g. "Can they fire me without notice?"</p>
    )}
    {chatMessages.map((msg, i) => (
      <div key={i} className={`chat-msg ${msg.role}`}>
        {msg.content}
      </div>
    ))}
    {chatLoading && <div className="chat-msg assistant chat-typing">Thinking...</div>}
  </div>
  <div className="chat-input-row">
    <input
      type="text"
      placeholder="Ask anything about this document..."
      value={chatInput}
      onChange={(e) => setChatInput(e.target.value)}
      onKeyDown={(e) => e.key === "Enter" && sendChatMessage()}
      disabled={chatLoading}
    />
    <button onClick={sendChatMessage} disabled={chatLoading || !chatInput.trim()}>
      Send ↗
    </button>
  </div>
</div>

            <div className="action-row">
              <button className="btn-primary" onClick={downloadReport}>⬇ Download Full Report</button>
              <button className="btn-secondary" onClick={() => { setResult(null); setFile(null); }}>
                Analyze New Document
              </button>
            </div>
          </div>
        )}

        {!result && (
          <div className="trust-bar">
            <span className="trust-item">🔒 End-to-end secure</span>
            <span className="trust-item">⚡ Under 30 seconds</span>
            <span className="trust-item">🌍 100+ languages</span>
            <span className="trust-item">🤖 Powered by Claude AI</span>
          </div>
        )}
      </div>
    {showHowItWorks && (
        <div className="modal-overlay" onClick={() => setShowHowItWorks(false)}>
          <div className="modal-box" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>How LegalEase Works</h3>
              <button className="modal-close" onClick={() => setShowHowItWorks(false)}>✕</button>
            </div>
            <div className="modal-steps">
              <div className="modal-step">
                <div className="step-num">1</div>
                <div>
                  <h4>Upload your document</h4>
                  <p>Drop in any PDF — a contract, NDA, rental agreement, or employment letter.</p>
                </div>
              </div>
              <div className="modal-step">
                <div className="step-num">2</div>
                <div>
                  <h4>AI reads and analyzes it</h4>
                  <p>Our AI extracts every clause, checks for risky language, and scores the overall risk.</p>
                </div>
              </div>
              <div className="modal-step">
                <div className="step-num">3</div>
                <div>
                  <h4>Get instant plain-English insights</h4>
                  <p>See red flags, a risk score, and a clause-by-clause breakdown — all in under 30 seconds.</p>
                </div>
              </div>
            </div>
            <button className="modal-cta" onClick={() => {
              setShowHowItWorks(false);
              document.querySelector(".upload-box")?.scrollIntoView({ behavior: "smooth" });
            }}>
              Try it now
            </button>
          </div>
        </div>
      )}

      {showFeatures && (
        <div className="modal-overlay" onClick={() => setShowFeatures(false)}>
          <div className="modal-box" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Features</h3>
              <button className="modal-close" onClick={() => setShowFeatures(false)}>✕</button>
            </div>
            <div className="features-grid">
  <div className="feature-item">
    <span className="feature-icon">📄</span>
    <h4>Plain English Summaries</h4>
    <p>No legal jargon — every clause explained simply.</p>
  </div>
  <div className="feature-item">
    <span className="feature-icon">🚩</span>
    <h4>Red Flag Detection</h4>
    <p>Automatically spots dangerous or unfair clauses.</p>
  </div>
  <div className="feature-item">
    <span className="feature-icon">📊</span>
    <h4>Risk Scoring</h4>
    <p>Get an overall Low / Medium / High risk rating.</p>
  </div>
  <div className="feature-item">
    <span className="feature-icon">📑</span>
    <h4>Clause Breakdown</h4>
    <p>Every section explained with its own risk level.</p>
  </div>
  <div className="feature-item">
    <span className="feature-icon">💬</span>
    <h4>AI Chatbot</h4>
    <p>Ask questions about your document and get instant grounded answers.</p>
  </div>
  <div className="feature-item">
    <span className="feature-icon">💡</span>
    <h4>Negotiation Suggestions</h4>
    <p>Get exact wording to propose for fixing risky clauses.</p>
  </div>
  <div className="feature-item">
    <span className="feature-icon">📥</span>
    <h4>Downloadable PDF Report</h4>
    <p>Export the full analysis as a polished, shareable PDF.</p>
  </div>
  <div className="feature-item">
    <span className="feature-icon">🔒</span>
    <h4>Privacy First</h4>
    <p>Your document is processed and never stored.</p>
  </div>
</div>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;

